name: Test Output
on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'

jobs:
  test:
    container: rust:1.82.0
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Test Output
        run: ./test.sh